### ISSUE TITLE
MySqlSwiftNative convert to Swift 3 and Xcode 8

### ISSUE THREAD

**Issue by wmichel1** [mcorega/MySqlSwiftNative#13]
I have a project working perfectly with Swift 2. My system has updated to Swift 3 and Xcode 8. Some changes were necessairy and I converted the code to Swift 3. Unfortunately I was not able tot solve all issues.
Is there an project to migrate MySQLSwiftNative to swift 3? I would appreciate it.

**Comment by Jon-GHI** [comment]
Yes, like wmichel1, I also have a project requiring Swift 3 syntax. Please consider updating the code to Swift 3. Thank you in advance for your help.

**Comment by haemi** [comment]
would love this as well...

**Comment by sahandnayebaziz** [comment]
Hey @wmichel1 @Jon-GHI @haemi, Swift 3 support was merged into master in November!

https://github.com/mcorega/MySqlSwiftNative/pull/17
