### ISSUE TITLE
Errors in the iOS example

### ISSUE THREAD

**Issue by IAmTipsy** [mcorega/MySqlSwiftNative#2]
Hi guys, when i download and run the iOS example it gives me these errors. Is there any way to fix this?
![picture](https://cloud.githubusercontent.com/assets/3141532/12217359/0135fdc0-b6fe-11e5-9d00-3588b68d330a.png)

**Comment by mcorega** [comment]
I just pushed the latest changes. The iOS sample should work now. Use arrays when calling exec and query
