### ISSUE TITLE
How to implement a delete row?

### ISSUE THREAD

**Issue by mpapado3** [mcorega/MySqlSwiftNative#30]
I am trying to find out how to delete a row from database?

**Comment by TeddyCodeDev** [comment]
Set up your SQL Statement:

  Do {
        Let del_stmt = try con.prepare(“DELETE FROM {Table} Where {column} = ?”)
        Do{
             try del_stmt.exec([{variable to fill in ?}])
        } 
        catch (let err){
             print(err)
    }
    catch (let e){
         print(e)
    }

This is untested I wrote it on my phone but should work.

**Comment by mpapado3** [comment]
it worked, thank you!
