### ISSUE TITLE
What am i doing wroug

### ISSUE THREAD

**Issue by ourweb4** [mcorega/MySqlSwiftNative#5]
func loadmembers() {
      let user_id = userdata.user_id
        if user_id != 0 {
            memberlist.removeAll()
            opendb()
            do {
                var table = MySQL.Table(tableName:"members", connection:conn)
                // select all rows from the table given a condition
                 var rows = try table.select(Where: ["user_id=",user_id])
                    
                for var i = 0; i < rows!.count; i++ {
                    
                    var row = rows
                  
                    let member_id = (row["member_id"] as UInt)
                    
                    let optin = row["optin"] as? UInt
                    let name = row["name"] as? String
                    let cell = (row["cell"] as? String)!
                    
                    let addmember = members(member_id: member_id, user_id: user_id, name: name, cell: cell, opin: optin)
                    
                    memberlist.append(addmember)
                  //  }
                }
                
            }
             catch (let err as NSError) {
               print(err.debugDescription)

            }
            closedb()
            tableview.reloadData()
        }
    
    }

**Comment by mcorega** [comment]
are you using the latest sources from github? releases are older.

**Comment by ourweb4** [comment]
pods

**Comment by ourweb4** [comment]
https://github.com/ourweb4/smsrealtor.git

**Comment by mcorega** [comment]
copy the contents of Sources/MySqlSwiftNative/ to your project, delete the pods dependencies - they are old, and it should work

**Comment by ourweb4** [comment]
ok  how

**Comment by ourweb4** [comment]
same problem

**Comment by mcorega** [comment]
made some changes to your code, added the missing files. I also attached a zip containing the project which builds on my system.
[smsrealtor.zip](https://github.com/mcorega/MySqlSwiftNative/files/170529/smsrealtor.zip)

**Comment by ourweb4** [comment]
thanks
