### ISSUE TITLE
Problem querying rows with NULL fields

### ISSUE THREAD

**Issue by riccardo-tesio** [mcorega/MySqlSwiftNative#8]
When a cell contains NULL, then all the remaining cells in the row are returned with NULL values.

Fix: in `Utils.swift`,   `func lenEncStr(b:[UInt8]) ->(String?, Int)`, around line 213:
            `guard num != nil else {
                return (nil, 0)
            }`
should be changed with:

```
        `guard num != nil else {
            return (nil, n)
        }`
```

**Comment by sahandnayebaziz** [comment]
@riccardo-tesio can you open a PR with this fix?
